"""Tests for the DNA layer: parsing, comparison, phasing, simulation."""

from __future__ import annotations

import io
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from roots.dna import phase as phase_mod
from roots.dna import predict as predict_mod
from roots.dna import qc as qc_mod
from roots.dna import raw as raw_mod
from roots.dna import relate as relate_mod
from roots.dna import simulate as sim_mod
from roots.genome import GeneticMap, detect_build, normalize_chrom
from tests import helpers

TWENTYTHREE = """\
# This data file generated by 23andMe at: Wed Jan 01 00:00:00 2020
# Reference human assembly build 37
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tAA
rs3094315\t1\t752566\tAG
rs12124819\t1\t776546\t--
rs28569024\tX\t2699645\tG
rs2032658\tY\t2655180\tC
rs1556422\tMT\t16400\tT
"""

ANCESTRY = """\
#AncestryDNA raw data download
#All processing is done on build 37
rsid\tchromosome\tposition\tallele1\tallele2
rs4477212\t1\t82154\tA\tA
rs3094315\t1\t752566\tG\tA
rs12124819\t1\t776546\t0\t0
rs28569024\t23\t2699645\tG\tG
rs99999\t26\t16400\tT\tT
"""


def _write(text: str, suffix: str = ".txt") -> str:
    fd, path = tempfile.mkstemp(suffix=suffix)
    with os.fdopen(fd, "w") as fh:
        fh.write(text)
    return path


class TestGenome(unittest.TestCase):
    def test_chromosome_normalisation(self):
        self.assertEqual(normalize_chrom("chr7"), "7")
        self.assertEqual(normalize_chrom("23"), "X")
        self.assertEqual(normalize_chrom("24"), "Y")
        self.assertEqual(normalize_chrom("25"), "X", "PAR folds into X")
        self.assertEqual(normalize_chrom("26"), "MT")
        self.assertIsNone(normalize_chrom("99"))

    def test_linear_map_totals(self):
        gmap = GeneticMap.linear("37")
        total = gmap.autosomal_total_cm()
        self.assertGreater(total, 3400)
        self.assertLess(total, 3700)

    def test_map_is_monotone(self):
        gmap = GeneticMap.linear("37")
        a = gmap.cm_at("1", 10_000_000)
        b = gmap.cm_at("1", 100_000_000)
        self.assertLess(a, b)
        self.assertAlmostEqual(gmap.length_cm("1", 100_000_000, 10_000_000), b - a, places=6)

    def test_build_detection(self):
        # A coordinate past the GRCh38 end of chr1 can only be build 37.
        self.assertEqual(detect_build([("1", 249_000_000)]), "37")


class TestRawParsing(unittest.TestCase):
    def test_23andme(self):
        path = _write(TWENTYTHREE)
        try:
            info, records, stats = raw_mod.read_with_stats(path)
            rows = list(records)
            self.assertEqual(info.vendor, "23andMe")
            self.assertEqual(info.build, "37")
            self.assertEqual(len(rows), 6)
            self.assertEqual(rows[0], ("1", 82154, "rs4477212", "AA"))
            self.assertEqual(rows[2][3], "--", "no-calls normalise")
            self.assertEqual(rows[3], ("X", 2699645, "rs28569024", "G"))
            self.assertEqual(stats.called, 5)
        finally:
            os.unlink(path)

    def test_ancestry(self):
        path = _write(ANCESTRY)
        try:
            info, records, _ = raw_mod.read_with_stats(path)
            rows = list(records)
            self.assertEqual(info.vendor, "AncestryDNA")
            self.assertEqual(rows[1][3], "AG", "alleles are sorted, so GA becomes AG")
            self.assertEqual(rows[2][3], "--", "Ancestry writes no-calls as 0")
            self.assertEqual(rows[3][0], "X")
            self.assertEqual(rows[4][0], "MT")
        finally:
            os.unlink(path)

    def test_cross_vendor_agreement(self):
        """The same site read from two vendors must produce the same genotype."""
        p1, p2 = _write(TWENTYTHREE), _write(ANCESTRY)
        try:
            _, r1 = raw_mod.read(p1)
            _, r2 = raw_mod.read(p2)
            a = {(c, p): g for c, p, _, g in r1}
            b = {(c, p): g for c, p, _, g in r2}
            shared = set(a) & set(b)
            self.assertTrue(shared)
            for key in shared:
                if a[key] != "--" and b[key] != "--":
                    self.assertTrue(
                        qc_mod.same_call(a[key], b[key]),
                        f"vendors disagree at {key}: {a[key]} vs {b[key]}",
                    )
            # The X is where the two spellings genuinely differ: one vendor
            # writes a hemizygous call once, the other doubles it, and which
            # is correct depends on a sex the parser has not established yet.
            self.assertEqual(a[("X", 2699645)], "G")
            self.assertEqual(b[("X", 2699645)], "GG")
            self.assertTrue(qc_mod.same_call("G", "GG"))
            self.assertFalse(qc_mod.same_call("AG", "GG"))
        finally:
            os.unlink(p1)
            os.unlink(p2)

    def test_genotype_normalisation(self):
        self.assertEqual(raw_mod.normalize_genotype(["G", "A"]), "AG")
        self.assertEqual(raw_mod.normalize_genotype(["AG"]), "AG")
        self.assertEqual(raw_mod.normalize_genotype(["0", "0"]), "--")
        self.assertEqual(raw_mod.normalize_genotype(["A", "0"]), "--",
                         "a half-called site is unusable")
        self.assertEqual(raw_mod.normalize_genotype(["--"]), "--")


class TestIBS(unittest.TestCase):
    def test_states(self):
        self.assertEqual(qc_mod.ibs("AA", "AA"), 2)
        self.assertEqual(qc_mod.ibs("AG", "AG"), 2)
        self.assertEqual(qc_mod.ibs("AA", "AG"), 1)
        self.assertEqual(qc_mod.ibs("AA", "GG"), 0)
        self.assertEqual(qc_mod.ibs("AA", "--"), -1)


class TestComparison(unittest.TestCase):
    """Detect IBD from genotypes alone, with no vendor involved."""

    @classmethod
    def setUpClass(cls):
        cls.store, cls.child, cls.mother, cls.gmap, cls.path = helpers.parent_child_store()
        cls.cmp = relate_mod.compare(
            cls.store, cls.child, cls.mother, cls.gmap, min_cm=7.0, min_snps=20
        )

    @classmethod
    def tearDownClass(cls):
        helpers.cleanup(cls.store, cls.path)

    def test_parent_child_shares_whole_genome(self):
        genome = self.gmap.autosomal_total_cm()
        self.assertGreater(
            self.cmp.total_cm, genome * 0.90,
            "a parent and child are half-identical across essentially every "
            f"chromosome; got {self.cmp.total_cm:.0f} of {genome:.0f} cM",
        )

    def test_no_opposite_homozygotes(self):
        self.assertLess(
            self.cmp.ibs0_rate, 0.01,
            "opposite homozygotes are impossible between parent and child "
            "except through genotyping error",
        )

    def test_classification(self):
        verdict = relate_mod.classify_close(self.cmp, self.gmap)
        self.assertEqual(verdict.label, "parent/child")

    def test_verify_parent_gate(self):
        ok, _why = relate_mod.verify_parent(self.cmp, self.gmap)
        self.assertTrue(ok)

    def test_unrelated_pair_shares_little(self):
        store, a, b, gmap, path = helpers.unrelated_store()
        try:
            cmp = relate_mod.compare(store, a, b, gmap, min_cm=7.0, min_snps=20)
            genome = gmap.autosomal_total_cm()
            self.assertLess(
                cmp.total_cm, genome * 0.35,
                "unrelated people should not look half-identical genome-wide",
            )
            ok, _ = relate_mod.verify_parent(cmp, gmap)
            self.assertFalse(ok, "the parent gate must reject unrelated kits")
        finally:
            helpers.cleanup(store, path)


class TestPhasing(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.store, cls.child, cls.mother, cls.gmap, cls.path = helpers.parent_child_store()
        cls.stats = phase_mod.phase_against_parent(
            cls.store, cls.child, cls.mother, parent_role="mother"
        )

    @classmethod
    def tearDownClass(cls):
        helpers.cleanup(cls.store, cls.path)

    def test_mendelian_rate_is_low(self):
        self.assertLess(
            self.stats.mendelian_rate, 0.01,
            f"got {self.stats.mendelian_rate:.3%}; a true parent-child pair "
            "should only violate Mendel through genotyping error",
        )

    def test_heterozygous_sites_mostly_resolve(self):
        self.assertGreater(
            self.stats.het_resolution_rate, 0.35,
            "a homozygous mother pins the transmitted allele; that should "
            "resolve roughly half of the child's heterozygous sites",
        )

    def test_phase_is_written(self):
        row = self.store.db.execute(
            "SELECT COUNT(*) FROM phased WHERE kit_id=? AND pat IS NOT NULL",
            (self.child,),
        ).fetchone()
        self.assertGreater(row[0], 1000)

    def test_export_produces_readable_kit(self):
        fd, out = tempfile.mkstemp(suffix=".txt")
        os.close(fd)
        try:
            counts = phase_mod.export_phased_kit(self.store, self.child, "paternal", out)
            self.assertGreater(counts["resolved"], 1000)
            info, records = raw_mod.read(out)
            rows = list(records)
            self.assertGreater(len(rows), 1000)
            for _c, _p, _r, gt in rows[:200]:
                self.assertIn(gt, ("--",) + tuple(a * 2 for a in "ACGTID"),
                              "a phased export is homozygous or missing, never het")
        finally:
            os.unlink(out)


class TestSimulator(unittest.TestCase):
    """The simulator is calibrated against relationships whose average
    sharing is well established from published data."""

    ITER = 300

    def _mean(self, key: str) -> float:
        rel = sim_mod.CATALOGUE[key]
        return sim_mod.simulate(rel, iterations=self.ITER, min_cm=7.0, seed=3).mean

    def test_parent_child_is_the_whole_genome(self):
        mean = self._mean("parent")
        self.assertGreater(mean, 3400)
        self.assertLess(mean, 3700)

    def test_full_siblings(self):
        # Published average 2613 cM.
        self.assertAlmostEqual(self._mean("sibling"), 2613, delta=180)

    def test_second_degree_relationships_agree_with_each_other(self):
        # Half siblings, grandparents and aunt/uncle all sit near 1750 cM.
        # That they land together is the point: total sharing cannot tell
        # them apart, which is what makes this range genealogically hard.
        for key in ("half_sibling", "gparent", "avuncular"):
            with self.subTest(relationship=key):
                self.assertAlmostEqual(self._mean(key), 1750, delta=220)

    def test_first_cousins(self):
        # Published average 866 cM.
        self.assertAlmostEqual(self._mean("1c"), 866, delta=150)

    def test_sharing_falls_by_half_each_cousin_degree(self):
        means = [self._mean(k) for k in ("1c", "2c", "3c")]
        for closer, further in zip(means, means[1:]):
            self.assertGreater(closer, further * 2.0)

    def test_distant_relatives_often_share_nothing(self):
        rel = sim_mod.CATALOGUE["4c"]
        dist = sim_mod.simulate(rel, iterations=self.ITER, min_cm=7.0, seed=5)
        self.assertGreater(
            dist.p_undetected, 0.15,
            "a substantial share of real fourth cousins share no detectable "
            "DNA, which is why a missing match proves nothing at this distance",
        )

    def test_full_siblings_have_fully_identical_regions(self):
        sibs = sim_mod.simulate(sim_mod.CATALOGUE["sibling"], iterations=100, seed=2)
        cousins = sim_mod.simulate(sim_mod.CATALOGUE["1c"], iterations=100, seed=2)
        self.assertGreater(sum(sibs.ibd2) / len(sibs.ibd2), 500)
        self.assertLess(sum(cousins.ibd2) / len(cousins.ibd2), 60,
                        "cousins should almost never be fully identical")


class TestIntervalAlgebra(unittest.TestCase):
    def test_matching_requires_same_label(self):
        a = [(0.0, 10.0, 1), (10.0, 20.0, 2)]
        b = [(0.0, 5.0, 1), (5.0, 20.0, 3)]
        self.assertEqual(sim_mod._matching(a, b), [(0.0, 5.0)])

    def test_union_merges_touching_spans(self):
        self.assertEqual(sim_mod._union([(0, 5), (5, 9), (20, 22)]), [(0, 9), (20, 22)])

    def test_intersect(self):
        self.assertEqual(sim_mod._intersect([(0, 10)], [(5, 20)]), [(5, 10)])


class TestPrediction(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        fd, cls.path = tempfile.mkstemp(suffix=".db")
        os.close(fd)
        os.unlink(cls.path)
        from roots.store import Store

        cls.store = Store(cls.path)
        cls.gmap = GeneticMap.linear("37")

    @classmethod
    def tearDownClass(cls):
        helpers.cleanup(cls.store, cls.path)

    def _top(self, cm: float, **kw) -> str:
        pred = predict_mod.predict(
            self.store, cm, gmap=self.gmap, iterations=300, **kw
        )
        return pred.candidates[0].rel.key

    def test_parent_level_sharing(self):
        self.assertIn(self._top(3480), ("parent", "twin"))

    def test_sibling_level_sharing(self):
        self.assertEqual(self._top(2600, ibd2_cm=850), "sibling")

    def test_prior_pulls_low_sharing_toward_distant_relatives(self):
        with_prior = self._top(60)
        flat = self._top(60, use_prior=False)
        self.assertNotEqual(
            with_prior, flat,
            "at 60 cM the sheer number of distant relatives should outweigh "
            "the better per-pair fit of a closer relationship",
        )

    def test_fit_rejects_an_impossible_claim(self):
        rel = sim_mod.CATALOGUE["3c"]
        fit = predict_mod.fit_hypothesis(
            self.store, rel, 900.0, gmap=self.gmap, iterations=300
        )
        self.assertFalse(fit.plausible)
        self.assertIn("higher", fit.comment)

    def test_fit_accepts_a_reasonable_claim(self):
        rel = sim_mod.CATALOGUE["1c"]
        fit = predict_mod.fit_hypothesis(
            self.store, rel, 870.0, gmap=self.gmap, iterations=300
        )
        self.assertTrue(fit.plausible)

    def test_relative_counts_grow_with_distance(self):
        counts = [
            predict_mod.expected_relative_count(sim_mod.CATALOGUE[k])
            for k in ("1c", "2c", "3c", "4c")
        ]
        for closer, further in zip(counts, counts[1:]):
            self.assertLess(closer, further)


class TestProjection(unittest.TestCase):
    def test_relationship_projects_onto_a_parent(self):
        from roots.hypothesis import project_to_parent

        # Your paternal first cousin once removed is your father's first cousin.
        rel = sim_mod.CATALOGUE["1c1r"]
        projected = project_to_parent(rel)
        self.assertIsNotNone(projected)
        self.assertEqual(projected.up, rel.up - 1)
        self.assertEqual(projected.down, rel.down)

    def test_your_half_sibling_is_your_parents_child(self):
        from roots.hypothesis import project_to_parent

        rel = sim_mod.CATALOGUE["half_sibling"]
        projected = project_to_parent(rel)
        self.assertEqual(projected.up, 0)
        self.assertEqual(projected.name, "parent/child")


if __name__ == "__main__":
    unittest.main(verbosity=2)
